//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtWashingtonFeed.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://www.mountwashington.org/weather/conditions.png</string>
  <string>http://www.mountwashington.org/weather/cam/deck/deck-med.jpg</string>
  <string>http://www.mountwashington.org/weather/cam/north/north-med.jpg</string>
  <string>http://www.mountwashington.org/weather/cam/west/west-med.jpg</string>
  <string>http://www.mountwashington.org/weather/cam/ravines/ravines-med.jpg</string>
  <string>http://www.mountwashington.org/weather/cam/attitash/attitash-med.jpg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FeedCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FeedCollection"]));
            }
            set {
                this["FeedCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int FeedInterval {
            get {
                return ((int)(this["FeedInterval"]));
            }
            set {
                this["FeedInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadPath {
            get {
                return ((string)(this["DownloadPath"]));
            }
            set {
                this["DownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FeedEnabled {
            get {
                return ((bool)(this["FeedEnabled"]));
            }
            set {
                this["FeedEnabled"] = value;
            }
        }
    }
}
